[[language]]
name = "toml"
indent = { tab-width = 2, unit = "	" }

[[language]]
name = "html"
indent = { tab-width = 2, unit = "	" }

[[language]]
name = "css"
indent = { tab-width = 2, unit = "	" }

[[language]]
name = "scss"
indent = { tab-width = 2, unit = "	" }

[[language]]
name = "javascript"
indent = { tab-width = 2, unit = "	" }

[[language]]
name = "typescript"
indent = { tab-width = 2, unit = "	" }

[[language]]
name = "jsx"
indent = { tab-width = 2, unit = "	" }

[[language]]
name = "tsx"
indent = { tab-width = 2, unit = "	" }

[[language]]
name = "vue"
indent = { tab-width = 2, unit = "	" }
language-server = { command = "vue-language-server", args = ["--stdio"] }

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "	" }
language-server = { command = "rustup", args = ["run stable rust-analyzer --stdio"] }
